# Generated by pip2nix 0.8.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Pygments" = super.buildPythonPackage {
    name = "Pygments-2.3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/69/413708eaf3a64a6abb8972644e0f20891a55e621c6759e2c3f3891e05d63/Pygments-2.3.1.tar.gz";
      sha256 = "0ji87g09jph8jqcvclgb02qvxasdnr9pzvk90rl66d90yqcxmyjz";
    };
  };
  "bleach" = super.buildPythonPackage {
    name = "bleach-3.1.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."webencodings"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/5a/0df03e8735cd9c75167528299c738702437589b9c71a849489d00ffa82e8/bleach-3.1.0.tar.gz";
      sha256 = "1yhrgrhkln8bd6gn3imj69g1h4xqah9gaz9q26crqr6gmmvpzprz";
    };
  };
  "certifi" = super.buildPythonPackage {
    name = "certifi-2019.3.9";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/b8/d1ea38513c22e8c906275d135818fee16ad8495985956a9b7e2bb21942a1/certifi-2019.3.9.tar.gz";
      sha256 = "1bnpw7hrf9i1l9gfxjnzi45hkrvzz0pyn9ia8m4mw7sxhgb08qdj";
    };
  };
  "chardet" = super.buildPythonPackage {
    name = "chardet-3.0.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz";
      sha256 = "1bpalpia6r5x1kknbk11p1fzph56fmmnp405ds8icksd3knr5aw4";
    };
  };
  "check-manifest" = super.buildPythonPackage {
    name = "check-manifest-0.38";
    doCheck = false;
    propagatedBuildInputs = [
      self."toml"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/c3/99f1dc28ef1b743fd8b53c7fd07bb1502ec658a495b8d2e0f02610d6c2f7/check-manifest-0.38.tar.gz";
      sha256 = "08xkgx4a2jminzg8by15cdndxjhz6ff4r0ghnhzgin3l72g7996v";
    };
  };
  "colorama" = super.buildPythonPackage {
    name = "colorama-0.4.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/53/e785891dce0e2f2b9f4b4ff5bc6062a53332ed28833c7afede841f46a5db/colorama-0.4.1.tar.gz";
      sha256 = "0ba247bx5pc60hcpbf3rjsqk0whilg241i9qdfnlcwij5qgdgvh5";
    };
  };
  "docutils" = super.buildPythonPackage {
    name = "docutils-0.14";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz";
      sha256 = "0x22fs3pdmr42kvz6c654756wja305qv6cx1zbhwlagvxgr4xrji";
    };
  };
  "gocept.zestreleaser.customupload" = super.buildPythonPackage {
    name = "gocept.zestreleaser.customupload-3.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."setuptools"
      self."six"
      self."zest.releaser"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/6a/b2c181d572df6027271531f4d17e9bea9452130d9a8b2cb64f3e91339072/gocept.zestreleaser.customupload-3.0.tar.gz";
      sha256 = "157iifvcqm60x9yjvyg4krqn7s6jphn8mym69f24l37m44zkwb64";
    };
  };
  "idna" = super.buildPythonPackage {
    name = "idna-2.8";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/13/eb56951b6f7950cadb579ca166e448ba77f9d24efc03edd7e55fa57d04b7/idna-2.8.tar.gz";
      sha256 = "01rlkigdxg17sf9yar1jl8n18ls59367wqh59hnawlyg53vb6my3";
    };
  };
  "pkginfo" = super.buildPythonPackage {
    name = "pkginfo-1.5.0.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/04/fd6683d24581894be8b25bc8c68ac7a0a73bf0c4d74b888ac5fe9a28e77f/pkginfo-1.5.0.1.tar.gz";
      sha256 = "1fs825s0vrylg45rj16nm0vmnhvpbc233gsb8banq60wa74g493l";
    };
  };
  "pyroma" = super.buildPythonPackage {
    name = "pyroma-2.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."docutils"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/e4/540694eb7116c1557244f3d5c656673cea48674cb40759a78bf7bbc14c47/pyroma-2.4.tar.gz";
      sha256 = "0zzfnrrpydj44d5bg47fqhbg4mi5j23v9j3ssfdzyswpfyq1r8cl";
    };
  };
  "python-gettext" = super.buildPythonPackage {
    name = "python-gettext-4.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/86/64/1475ff167cf6e6b6f9e50973900011cb53be8260010e3d016ad3778c4565/python-gettext-4.0.tar.gz";
      sha256 = "00pcqwpnir0cr5lynima9ra1y4na1pk51x8c8v1jz2dca4d50sv2";
    };
  };
  "readme-renderer" = super.buildPythonPackage {
    name = "readme-renderer-24.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."Pygments"
      self."bleach"
      self."docutils"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/44/de/a567140b13a0fc8d3b04d85a510b5a7d9869b44b2939fa8ac07c5e421485/readme_renderer-24.0.tar.gz";
      sha256 = "0br0562lnvj339f1nwz4nfl4ay49rw05xkqacigzf9wz4mdza5mv";
    };
  };
  "requests" = super.buildPythonPackage {
    name = "requests-2.21.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/2c/514e4ac25da2b08ca5a464c50463682126385c4272c18193876e91f4bc38/requests-2.21.0.tar.gz";
      sha256 = "13jr0wkj9c2j8c0c8iaal9iivi0bpxghnsdn6lxcpnmc657q4ajh";
    };
  };
  "requests-toolbelt" = super.buildPythonPackage {
    name = "requests-toolbelt-0.9.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."requests"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/28/30/7bf7e5071081f761766d46820e52f4b16c8a08fef02d2eb4682ca7534310/requests-toolbelt-0.9.1.tar.gz";
      sha256 = "1h3gm88dcjbd7gm229a7x5qkkhnsqsjz0m0l2xyavm2ab3a8k04n";
    };
  };
  "setuptools" = super.buildPythonPackage {
    name = "setuptools-41.0.1";
    doCheck = false;
    nativeBuildInputs = [
      pkgs."unzip"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/64/a18a487b4391a05b9c7f938b94a16d80305bf0369c6b0b9509e86165e1d3/setuptools-41.0.1.zip";
      sha256 = "04sns22y2hhsrwfy1mha2lgslvpjsjsz8xws7h2rh5a7ylkd28m2";
    };
  };
  "six" = super.buildPythonPackage {
    name = "six-1.12.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/bf/4138e7bfb757de47d1f4b6994648ec67a51efe58fa907c1e11e350cddfca/six-1.12.0.tar.gz";
      sha256 = "0wxs1q74v07ssjywbbm7x6h5v9qx209ld2yfsif4060sxi0h2sni";
    };
  };
  "toml" = super.buildPythonPackage {
    name = "toml-0.10.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/19/5cbd78eac8b1783671c40e34bb0fa83133a06d340a38b55c645076d40094/toml-0.10.0.tar.gz";
      sha256 = "0p1xww2mzkhqvxkfvmfzm58bbfj812zhdz4rwdjiv94ifz2q37r2";
    };
  };
  "tqdm" = super.buildPythonPackage {
    name = "tqdm-4.31.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/9b/f3036a9a11c250eb51d38acf94d1d7c33a0d4da8a8931bfdf15e12d505b1/tqdm-4.31.1.tar.gz";
      sha256 = "01fdks20qx09xw3zdxda6ybiqlycjy8zppgnc8izfqg9xgipfag2";
    };
  };
  "twine" = super.buildPythonPackage {
    name = "twine-1.13.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."pkginfo"
      self."readme-renderer"
      self."requests"
      self."requests-toolbelt"
      self."setuptools"
      self."tqdm"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/af/4f5bfaa8e9c0ddce229b058a4ebdc11a6e05e9c2e51b854d1d0e8f764d09/twine-1.13.0.tar.gz";
      sha256 = "1p0lbgzz14i00g7a9x8rw5q5fpbwz2hkm8cz3ndlxiyg7s9rrhnn";
    };
  };
  "urllib3" = super.buildPythonPackage {
    name = "urllib3-1.24.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/3c/1bb7ef6c435dea026f06ed9f3ba16aa93f9f4f5d3857a51a35dfa00882f1/urllib3-1.24.3.tar.gz";
      sha256 = "1x0slqrv6kixkbcdnxbglvjliwhc1payavxjvk8fvbqjrnasd4r3";
    };
  };
  "webencodings" = super.buildPythonPackage {
    name = "webencodings-0.5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/02/ae6ceac1baeda530866a85075641cec12989bd8d31af6d5ab4a3e8c92f47/webencodings-0.5.1.tar.gz";
      sha256 = "08qrgrc4hrximb2gqnl69g01s93rhf2842jfxdjljc1dbwj1qsmk";
    };
  };
  "wheel" = super.buildPythonPackage {
    name = "wheel-0.33.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/cf/1ea0f5b3ce55cacde1e84cdde6cee1ebaff51bd9a3e6c7ba4082199af6f6/wheel-0.33.1.tar.gz";
      sha256 = "178fix20jymknzx8qs6iqh6zc9rbxzd750q99dkbnxw9y9vgva36";
    };
  };
  "zest.pocompile" = super.buildPythonPackage {
    name = "zest.pocompile-1.4";
    doCheck = false;
    nativeBuildInputs = [
      pkgs."unzip"
    ];
    propagatedBuildInputs = [
      self."python-gettext"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/44/42/6189f119fa6776c7725da9fbc767886f38ace040297d559785640591f9ad/zest.pocompile-1.4.zip";
      sha256 = "1krha8srg91clp2schxj0i2hyc11j07bxqbybcjzblp0nsv0ivsz";
    };
  };
  "zest.releaser" = super.buildPythonPackage {
    name = "zest.releaser-6.18.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."chardet"
      self."check-manifest"
      self."colorama"
      self."pyroma"
      self."readme-renderer"
      self."requests"
      self."setuptools"
      self."six"
      self."twine"
      self."wheel"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/54/4a/0d9f3eac02cda49fff11d583ed4f0a943751e3270c6ebf1f9c1a14abcac5/zest.releaser-6.18.2.tar.gz";
      sha256 = "1p0b96dfwbyrlvvn9p3v7vfx7mgsl93sarjwg5hrkf9ml7cm6y0j";
    };
  };
}
