# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "19.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl";
      sha256 = "0ybaycx149w1q2fqkjv119l83vx5115l8167bv5y2b9rxprdph39";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "backcall" = super.buildPythonPackage rec {
    pname = "backcall";
    version = "0.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz";
      sha256 = "1r01dqch3f8fdj3n6fviw8hxqrs6w5v0qw4izmvqzry1w9dxiv1q";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl";
      sha256 = "04rbcbf5p4kdc7ghlsddxrnglsvk4rsmzphnlxyfdfcmcdg0cd93";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click-plugins" = super.buildPythonPackage rec {
    pname = "click-plugins";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e9/da/824b92d9942f4e472702488857914bdd50f73021efea15b4cad9aca8ecef/click_plugins-1.1.1-py2.py3-none-any.whl";
      sha256 = "1j4zi013raj2nh35r0fwlp6ivr238hyn5qc1zmbm0br2sc3209jx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
    ];
  };
  "cligj" = super.buildPythonPackage rec {
    pname = "cligj";
    version = "0.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e4/be/30a58b4b0733850280d01f8bd132591b4668ed5c7046761098d665ac2174/cligj-0.5.0-py3-none-any.whl";
      sha256 = "052ggd9zb6y1cb34c21n5xvvcdmr25l9wff3mrcggqzxmgllrwi0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
    ];
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "4.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl";
      sha256 = "1xng99yyb5rv7g0zbmz0g5dhnjj5g0idx3r5lm5pbjih32hg6sgh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "fiona" = super.buildPythonPackage rec {
    pname = "fiona";
    version = "1.8.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/9d/63696e7b1de42aad294d4781199a408bec593d8fdb80a2b4a788c911a33b/Fiona-1.8.6.tar.gz";
      sha256 = "0gpvdrayam4qvpqvz0911nlyvf7ib3slsyml52qx172vhpldycgs";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."click"
      self."click-plugins"
      self."cligj"
      self."munch"
      self."six"
    ];
  };
  "ipykernel" = super.buildPythonPackage rec {
    pname = "ipykernel";
    version = "5.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d4/16/43f51f65a8a08addf04f909a0938b06ba1ee1708b398a9282474531bd893/ipykernel-5.1.2-py3-none-any.whl";
      sha256 = "10s3hqlfgsm1livr72b5jgpzpq5hmh2rjx3cnxhf1xahhkq3wz0n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython"
      self."jupyter-client"
      self."tornado"
      self."traitlets"
    ];
  };
  "ipython" = super.buildPythonPackage rec {
    pname = "ipython";
    version = "7.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fb/44/f28a13852e562af719f9de1761680a84a93e8b4c50e22d00d68f60ee2e8b/ipython-7.8.0-py3-none-any.whl";
      sha256 = "16zfbmgdjksbj6v82kg1jx24dk0zg9p2hpj0isk407k445ch1ay4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."backcall"
      self."decorator"
      self."jedi"
      self."pexpect"
      self."pickleshare"
      self."prompt-toolkit"
      self."pygments"
      self."setuptools"
      self."traitlets"
    ];
  };
  "ipython-genutils" = super.buildPythonPackage rec {
    pname = "ipython-genutils";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl";
      sha256 = "1f7sc4ydjj33gadcgfz8fcx02d1wm2frlqwzdik1krlr6wikgpbj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jedi" = super.buildPythonPackage rec {
    pname = "jedi";
    version = "0.15.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/54/da994f359e4e7da4776a200e76dbc85ba5fc319eefc22e33d55296d95a1d/jedi-0.15.1-py2.py3-none-any.whl";
      sha256 = "09qsq9m1scqag5m8jqjxvqns5fmqh7npz832f7bnzw72h0ynqsvq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."parso"
    ];
  };
  "jupyter-client" = super.buildPythonPackage rec {
    pname = "jupyter-client";
    version = "5.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/4c/bf613864ae0644e2ac7d4a40bd209c40c8c71e3dc88d5f1d0aa92a68e716/jupyter_client-5.3.1-py2.py3-none-any.whl";
      sha256 = "1cv50i481kq1b7f56kg8nzxjz35mvmzm688mrjnhgyjajsi0ka3k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-core"
      self."python-dateutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-core" = super.buildPythonPackage rec {
    pname = "jupyter-core";
    version = "4.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/25/6ffb0f6e57fa6ef5d2f814377133b361b42a6dd39105f4885a4f1666c2c3/jupyter_core-4.5.0-py2.py3-none-any.whl";
      sha256 = "114bipndb6z5zg5pnm821z3padb94cljvwlmr43liwr5rzb25ypl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."traitlets"
    ];
  };
  "munch" = super.buildPythonPackage rec {
    pname = "munch";
    version = "2.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/f4/260ec98ea840757a0da09e0ed8135333d59b8dfebe9752a365b04857660a/munch-2.3.2.tar.gz";
      sha256 = "0l8d9d0sd85jskwzjnhz4apivnih4625pamq5xrwzskzhdmx5qva";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "parso" = super.buildPythonPackage rec {
    pname = "parso";
    version = "0.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a3/bd/bf4e5bd01d79906e5b945a7af033154da49fd2b0d5b5c705a21330323305/parso-0.5.1-py2.py3-none-any.whl";
      sha256 = "1p4p4wij05pckcwpwplnhl5pblj68frbci17gylmvnzsw4rl51b3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pexpect" = super.buildPythonPackage rec {
    pname = "pexpect";
    version = "4.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/3e/377007e3f36ec42f1b84ec322ee12141a9e10d808312e5738f52f80a232c/pexpect-4.7.0-py2.py3-none-any.whl";
      sha256 = "1lawiraiqlfvic4fgrz0qzjphj0s5j39184szgdiyypkzkyyx510";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
  };
  "pickleshare" = super.buildPythonPackage rec {
    pname = "pickleshare";
    version = "0.7.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl";
      sha256 = "0mnzcb714ynl1qlv9dwnh50rv75mmj18ywaxbl8xzm3l9m0syjcn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prompt-toolkit" = super.buildPythonPackage rec {
    pname = "prompt-toolkit";
    version = "2.0.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f7/a7/9b1dd14ef45345f186ef69d175bdd2491c40ab1dfa4b2b3e4352df719ed7/prompt_toolkit-2.0.9-py3-none-any.whl";
      sha256 = "101p8qhz3ri83g3rw30x53ymm2iysp880x97ri2nsslrk8wg7b8i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
      self."wcwidth"
    ];
  };
  "ptyprocess" = super.buildPythonPackage rec {
    pname = "ptyprocess";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl";
      sha256 = "07yaymg8cpnh675miwk62gf20d33sddk6h567i144qz7fs6m5k6p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pygments" = super.buildPythonPackage rec {
    pname = "pygments";
    version = "2.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl";
      sha256 = "09q1bggw7yxwx2ayqskg3ml7yh6j66rxkh8a007l72n8hny31r3i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl";
      sha256 = "1yzj7m4h5babisvqac674xx82a8gd7ynxqhm2rwj7mpf9b3q8rby";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "pyzmq" = super.buildPythonPackage rec {
    pname = "pyzmq";
    version = "18.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7a/d2/1eb3a994374802b352d4911f3317313a5b4ea786bc830cc5e343dad9b06d/pyzmq-18.1.0.tar.gz";
      sha256 = "1cxybx8j9zr8s1vv7f54ylyaz80svd1hx68n780lq8v9vcwlgx4k";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "setuptools" = super.buildPythonPackage rec {
    pname = "setuptools";
    version = "41.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl";
      sha256 = "1p20h1z8qzlzs33fjw0wnnr87khdd5npqs1dl9dimzag5b7sp023";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "shapely" = super.buildPythonPackage rec {
    pname = "shapely";
    version = "1.6.4.post2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz";
      sha256 = "03r42fmd9alp6r3q95ad6rldq2f7n1wimrw53zy5kpn33yv7pf64";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl";
      sha256 = "073nyd09fqi2xwalmsi2lf8lrwnma85hscs84iaizcam0ngq0l1k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tornado" = super.buildPythonPackage rec {
    pname = "tornado";
    version = "6.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/30/78/2d2823598496127b21423baffaa186b668f73cd91887fcef78b6eade136b/tornado-6.0.3.tar.gz";
      sha256 = "1afpxpv75zi1zvj2b3s6d7r4s4p0z2byh7jv9h3i4sb1p8vdnif8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "traitlets" = super.buildPythonPackage rec {
    pname = "traitlets";
    version = "4.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl";
      sha256 = "1nf72xiap5frnlariklymgxrh0pk99xwwwgs82mbvaf5axpmxjy6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
      self."ipython-genutils"
      self."six"
    ];
  };
  "wcwidth" = super.buildPythonPackage rec {
    pname = "wcwidth";
    version = "0.1.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl";
      sha256 = "0z6yi9wgxisnsz14c5zpz123bd2rslg7cgsmcjl40yxg4lcygszl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
