# Generated by pip2nix 0.7.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "click" = super.buildPythonPackage {
    name = "click-6.7";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/95/d9/c3336b6b5711c3ab9d1d3a80f1a3e2afeb9d8c02a7166462f6cc96570897/click-6.7.tar.gz";
      sha256 = "02qkfpykbq35id8glfgwc38yc430427yd05z1wc5cnld8zgicmgi";
    };
  };
  "click-plugins" = super.buildPythonPackage {
    name = "click-plugins-1.0.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."click"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/77/05/da5c9e19457f20cadfe22c397cd3852577066066f63e40f2baa0831b1693/click-plugins-1.0.3.tar.gz";
      sha256 = "1ifphgaw5mmcdnqd0qfnmrbm62q3k6p573aff4cxgpyjxmz5xk3s";
    };
  };
  "cligj" = super.buildPythonPackage {
    name = "cligj-0.4.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."click"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/fc/53/b89c392f33aa48b3063ad49e4dab70e424659d1fc4103b28b183f477f476/cligj-0.4.0.tar.gz";
      sha256 = "0m1zic66nay2rymfa9krd3jfpyajxjnbmzw7c2q764aw9ychgb8j";
    };
  };
  "decorator" = super.buildPythonPackage {
    name = "decorator-4.2.1";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/70/f1/cb9373195639db13063f55eb06116310ad691e1fd125e6af057734dc44ea/decorator-4.2.1.tar.gz";
      sha256 = "03iaf116rm3w8b4agb8hzf6z9331mrvi4khfxq35zkx17sgxsikx";
    };
  };
  "fiona" = super.buildPythonPackage {
    name = "fiona-1.7.11.post1";
    doCheck = false;
    propagatedBuildInputs = [
      self."cligj"
      self."click-plugins"
      self."six"
      self."munch"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/67/5f/bb390a10c9c3722c69bef7df1e721c604a204106ac4398b534a2018e4901/Fiona-1.7.11.post1.tar.gz";
      sha256 = "1grsmp7x6p04688c6i85vbhrdpqfzj0l4p8g8lhb9rh5m17h9prm";
    };
  };
  "ipykernel" = super.buildPythonPackage {
    name = "ipykernel-4.8.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipython"
      self."traitlets"
      self."jupyter-client"
      self."tornado"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/52/a6/8cfaaa3a1ccdebe7f3eabcf6969101e32dbdf14bfb2443d1c021130ce23c/ipykernel-4.8.2.tar.gz";
      sha256 = "13rw8nsadbx1lc3vr43563d7flp1p7l0cjlwvl6p3mzss2fl94f0";
    };
  };
  "ipython" = super.buildPythonPackage {
    name = "ipython-6.2.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."setuptools"
      self."jedi"
      self."decorator"
      self."pickleshare"
      self."simplegeneric"
      self."traitlets"
      self."prompt-toolkit"
      self."pygments"
      self."pexpect"
      self."pexpect"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/fa/50/974211502bd72873728d44c3013fe79875c819c8fb69f778bcfd67bc7d38/ipython-6.2.1.tar.gz";
      sha256 = "022n6lcqx1x51yzgj1f9bj0rc08i6hdbbili3j6qk6dqr2k5ihai";
    };
  };
  "ipython-genutils" = super.buildPythonPackage {
    name = "ipython-genutils-0.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/e8/69/fbeffffc05236398ebfcfb512b6d2511c622871dca1746361006da310399/ipython_genutils-0.2.0.tar.gz";
      sha256 = "1a4bc9y8hnvq6cp08qs4mckgm6i6ajpndp4g496rvvzcfmp12bpb";
    };
  };
  "jedi" = super.buildPythonPackage {
    name = "jedi-0.11.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."parso"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/d2/41/430b325e411d564b1afc37bc7286c3549f4c415ada750a617fb1943c593d/jedi-0.11.1.tar.gz";
      sha256 = "15zsb7pqvjfkhg87g9jni51qa8igqd3xw80gxmcr9phs9p89kryn";
    };
  };
  "jupyter-client" = super.buildPythonPackage {
    name = "jupyter-client-5.2.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."traitlets"
      self."jupyter-core"
      self."pyzmq"
      self."python-dateutil"
      self."tornado"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/bf/0b/7e1725b5ef8925867a604ab74e0618e84fbe4b171996631996b02b99a752/jupyter_client-5.2.2.tar.gz";
      sha256 = "1i06kf88c3ldqi6i31bai65gi5zsp4zzaf9rrnfggn7h68qy5mc3";
    };
  };
  "jupyter-core" = super.buildPythonPackage {
    name = "jupyter-core-4.4.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/b6/2d/2804f4de3a95583f65e5dcb4d7c8c7183124882323758996e867f47e72af/jupyter_core-4.4.0.tar.gz";
      sha256 = "1dy083rarba8prn9f9srxq3c7n7vyql02ycrqq306c40lr57aw5s";
    };
  };
  "munch" = super.buildPythonPackage {
    name = "munch-2.2.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/92/58/c17cf679a2b9b65541cc71ba13a950289b7d34dd0967e34b8816a4d87044/munch-2.2.0.tar.gz";
      sha256 = "05dawxaki7ckd9cp1dq00njha29ylr9azrl8n1ja8rg932rlzyv2";
    };
  };
  "parso" = super.buildPythonPackage {
    name = "parso-0.1.1";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/14/3b/15cfd9c7a8bd9e3a2fe956e20fbc4e7c5768e06aea347d8eb68a05a71653/parso-0.1.1.tar.gz";
      sha256 = "1yyg0d15cnhvb50i7a9inrf060i5dh44zxfnqprnamjf4pzg65aq";
    };
  };
  "pexpect" = super.buildPythonPackage {
    name = "pexpect-4.4.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/fa/c3/60c0cbf96f242d0b47a82e9ca634dcd6dcb043832cf05e17540812e1c707/pexpect-4.4.0.tar.gz";
      sha256 = "0zg40ddbs9xy0lcysnv2l93kj369vp5874kwbrdkv3lnclammf37";
    };
  };
  "pickleshare" = super.buildPythonPackage {
    name = "pickleshare-0.7.4";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/69/fe/dd137d84daa0fd13a709e448138e310d9ea93070620c9db5454e234af525/pickleshare-0.7.4.tar.gz";
      sha256 = "0yvk14dzxk7g6qpr7iw23vzqbsr0dh4ij4xynkhnzpfz4xr2bac4";
    };
  };
  "prompt-toolkit" = super.buildPythonPackage {
    name = "prompt-toolkit-1.0.15";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."wcwidth"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8a/ad/cf6b128866e78ad6d7f1dc5b7f99885fb813393d9860778b2984582e81b5/prompt_toolkit-1.0.15.tar.gz";
      sha256 = "05v9h5nydljwpj5nm8n804ms0glajwfy1zagrzqrg91wk3qqi1c5";
    };
  };
  "ptyprocess" = super.buildPythonPackage {
    name = "ptyprocess-0.5.2";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/51/83/5d07dc35534640b06f9d9f1a1d2bc2513fb9cc7595a1b0e28ae5477056ce/ptyprocess-0.5.2.tar.gz";
      sha256 = "0ra31k10v3629xq0kdn8lwmfbi97anmk48r03yvh7mks0kq96hg6";
    };
  };
  "pygments" = super.buildPythonPackage {
    name = "pygments-2.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/71/2a/2e4e77803a8bd6408a2903340ac498cb0a2181811af7c9ec92cb70b0308a/Pygments-2.2.0.tar.gz";
      sha256 = "1k78qdvir1yb1c634nkv6rbga8wv4289xarghmsbbvzhvr311bnv";
    };
  };
  "python-dateutil" = super.buildPythonPackage {
    name = "python-dateutil-2.6.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/54/bb/f1db86504f7a49e1d9b9301531181b00a1c7325dc85a29160ee3eaa73a54/python-dateutil-2.6.1.tar.gz";
      sha256 = "1jkahssf0ir5ssxc3ydbp8cpv77limn8d4s77szb2nrgl2r3h749";
    };
  };
  "pyzmq" = super.buildPythonPackage {
    name = "pyzmq-17.0.0";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/9f/f6/85a33a25128a4a812c3482547e3d458eebdb19ee0b4699f9199cdb2ad731/pyzmq-17.0.0.tar.gz";
      sha256 = "1w63v3213yfzzj147ilnbryy6dmw3g8rwfks0iggchcv2dcswi81";
    };
  };
  "setuptools" = super.buildPythonPackage {
    name = "setuptools-38.5.2";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/e0/02/2b14188e06ddf61e5b462e216b15d893e8472fca28b1b0c5d9272ad7e87c/setuptools-38.5.2.zip";
      sha256 = "0r4hilfa8a274bqf2rmhj4l5wcpbb2xx3p1v2s3zdback0z14il2";
    };
  };
  "shapely" = super.buildPythonPackage {
    name = "shapely-1.6.4.post1";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/7d/3c/0f09841db07aabf9cc387662be646f181d07ed196e6f60ce8be5f4a8f0bd/Shapely-1.6.4.post1.tar.gz";
      sha256 = "1wh2rwpzribr3qlah9zhvk5w82v6s4ly5h4dvw14hl8isdr7bprh";
    };
  };
  "simplegeneric" = super.buildPythonPackage {
    name = "simplegeneric-0.8.1";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/3d/57/4d9c9e3ae9a255cd4e1106bb57e24056d3d0709fc01b2e3e345898e49d5b/simplegeneric-0.8.1.zip";
      sha256 = "0wwi1c6md4vkbcsfsf8dklf3vr4mcdj4mpxkanwgb6jb1432x5yw";
    };
  };
  "six" = super.buildPythonPackage {
    name = "six-1.11.0";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz";
      sha256 = "1scqzwc51c875z23phj48gircqjgnn3af8zy2izjwmnlxrxsgs3h";
    };
  };
  "tornado" = super.buildPythonPackage {
    name = "tornado-5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/59/4b/2c992ec4feb904471125702ed1dd3c912de1630c03bd555c3b05a41da93e/tornado-5.0.tar.gz";
      sha256 = "1aii2w25f6nss8scqxphc0kvqs2h20174wk11nq99sk15ib59xv2";
    };
  };
  "traitlets" = super.buildPythonPackage {
    name = "traitlets-4.3.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipython-genutils"
      self."six"
      self."decorator"
    ];
    src = fetchurl {
      url = "https://pypi.python.org/packages/a5/98/7f5ef2fe9e9e071813aaf9cb91d1a732e0a68b6c44a32b38cb8e14c3f069/traitlets-4.3.2.tar.gz";
      sha256 = "0dbq7sx26xqz5ixs711k5nc88p8a0nqyz6162pwks5dpcz9d4jww";
    };
  };
  "wcwidth" = super.buildPythonPackage {
    name = "wcwidth-0.1.7";
    doCheck = false;
    src = fetchurl {
      url = "https://pypi.python.org/packages/55/11/e4a2bb08bb450fdbd42cc709dd40de4ed2c472cf0ccb9e64af22279c5495/wcwidth-0.1.7.tar.gz";
      sha256 = "0pn6dflzm609m4r3i8ik5ni9ijjbb5fa3vg1n7hn6vkd49r77wrx";
    };
  };

### Test requirements

  
}
