# Generated by pip2nix 0.8.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "django" = super.buildPythonPackage {
    name = "django-2.1.7";
    doCheck = false;
    propagatedBuildInputs = [
      self."pytz"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/ae/29c28f6afddae0e305326078f31372f03d7f2e6d6210c9963843196ce67e/Django-2.1.7.tar.gz";
      sha256 = "0qvrcvlvd4866vjzf62nwwnvpy7534mgi3jx9pbm6zadsglm55lk";
    };
  };
  "pytz" = super.buildPythonPackage {
    name = "pytz-2018.9";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/be/6c59e30e208a5f28da85751b93ec7b97e4612268bb054d0dff396e758a90/pytz-2018.9.tar.gz";
      sha256 = "0k1pqnq3c4gvcspjxf3fschdjn71fk89i4wz801rxqh7f145xw6m";
    };
  };
}
